# Japanese/Japan translation of WireCloud.
# Copyright (C) 2015-2016 CoNWeT Lab., Universidad Politécnica de Madrid
# Copyright (C) 2019 Kazuhito Suda
# This file is distributed under the same license as the WireCloud package.
# Álvaro Arranz García <aarranz@fi.upm.es>, 2015-2016.
# Álvaro Arranz García <aarranz@ficodes.com>, 2018.
# Kazuhito Suda <k@fisuda.jp>, 2019
#
msgid ""
msgstr ""
"Project-Id-Version: WireCloud 1.3\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-03-15 00:00+0900\n"
"PO-Revision-Date: 2019-03-15 00:00+0900\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"Last-Translator: Kazuhito Suda <k@fisuda.jp>\n"
"Language-Team: Kazuhito Suda <k@fisuda.jp>\n"
"X-Generator: Poedit 2.2.1\n"

#: management/commands/addtocatalogue.py:82
msgid ""
"You must use at least one of the following flags: --redeploy, --users, --"
"groups or --public "
msgstr ""
"次のフラグの少なくとも1つを使用する必要があります: --redeploy, --users, --"
"groups または --public "

#: management/commands/addtocatalogue.py:99
#, python-format
msgid "Failed to read from %(file_name)s"
msgstr "%(file_name)s からの読み込みに失敗しました"

#: management/commands/addtocatalogue.py:112
#, python-format
msgid "Successfully imported \"%(name)s\" from \"%(file_name)s\""
msgstr "\"%(file_name)s\" から \"%(name)s\" を正常にインポートしました"

#: management/commands/addtocatalogue.py:114
#, python-format
msgid "Failed to import the mashable application component from %(file_name)s"
msgstr ""
"マッシュアップ・アプリケーションのコンポーネントを %(file_name)s からイン"
"ポートできませんでした"

#: models.py:44
msgid "Vendor"
msgstr "ベンダー"

#: models.py:45
msgid "Name"
msgstr "名前"

#: models.py:46
msgid "Version"
msgstr "バージョン"

#: models.py:47
msgid "Type"
msgstr "タイプ"

#: models.py:51
msgid "Available to all users"
msgstr "すべてのユーザが利用可能"

#: models.py:52
msgid "Users"
msgstr "ユーザ"

#: models.py:53
msgid "Groups"
msgstr "グループ"

#: models.py:62
msgid "templateURI"
msgstr "templateURI"

#: models.py:64
msgid "popularity"
msgstr "人気"

#: models.py:66
msgid "JSON description"
msgstr "JSON の説明"

#: utils.py:160 utils.py:165
#, python-format
msgid "Unable to process component description file: %s"
msgstr "コンポーネント記述ファイルを処理できません: %s"

#: utils.py:163
msgid "Unable to process component description file"
msgstr "コンポーネント記述ファイルを処理できません"

#: utils.py:175
#, python-format
msgid "Missing contents file: %(file_name)s."
msgstr "コンテンツ・ファイルがありません: %(file_name)s."

#: utils.py:181
#, python-format
msgid ""
"%(file_name)s was not encoded using the specified charset (%(charset)s "
"according to the widget descriptor file)."
msgstr ""
"%(file_name)s は、指定された文字セットを使用してエンコードされませんでした "
"(ウィジェット記述子ファイルに従った %(charset)s)."

#: views.py:77
msgid "Missing component file in the request"
msgstr "リクエストにコンポーネント・ファイルがありません"

#: views.py:88
msgid "The uploaded file is not a zip file"
msgstr "アップロードされたファイルは zip ファイルではありません"

#: views.py:94
msgid "Resource already exists"
msgstr "リソースは既に存在します"

#: views.py:99
msgid ""
"Error writing the resource into the filesystem. Please, contact the server "
"administrator."
msgstr ""
"ファイル・システムへのリソースの書き込み中にエラーが発生しました。"
"サーバ管理者に連絡してください。"

#: views.py:112
#, python-format
msgid "Invalid pagenum value: %s"
msgstr "無効な pagenum 値: %s"

#: views.py:130
#, python-format
msgid "Invalid maxresults value: %s"
msgstr "無効な maxresults 値: %s"

#: views.py:136
#, python-format
msgid "Orderby value not supported: %s"
msgstr "Orderby 値はサポートされていません: %s"

#: views.py:140
#, python-format
msgid "Scope value not supported: %s"
msgstr "スコープ値はサポートされていません: %s"

#: views.py:149
#, python-format
msgid "Scope value not supported: %s"
msgstr "スコープ値はサポートされていません: %s"

#: views.py:152
msgid "Forbidden"
msgstr "禁止"

#: views.py:188 views.py:198
#, python-format
msgid "user %(username)s is not the owner of the resource %(resource_id)s"
msgstr "ユーザ %(username)s はリソース %(resource_id)s の所有者ではありません"

#: views.py:240
msgid "Missing parameter: template_uri or file"
msgstr "パラメータがありません : template_uri または file"

#: views.py:260
msgid "Error opening the changelog file"
msgstr "変更履歴ファイルを開く際にエラーが発生しました"

#: views.py:286
#, python-format
msgid ""
"You can find the userguide of this component in this external <a target="
"\"_blank\" href=\"%s\">link</a>"
msgstr ""
"このコンポーネントのユーザ・ガイドは、この<a target=\"_blank\" href=\"%s\">"
"リンク</a>で見つけることができます"

#: views.py:302
msgid "Error opening the userguide file"
msgstr "ユーザ・ガイドのファイルを開く際にエラーが発生しました"
